import Tkinter as tk
from Tkinter import*

def login_page():
    f2.pack_forget()
    f5.pack_forget()
    f3.pack()
    f4.pack()
    f1.pack()
def register_page():
    f1.pack_forget()
    f3.pack_forget()
    f4.pack_forget()
    f2.pack()
    f5.pack()
master = tk.Tk()

# first frame - without f1.pack()
f1 = tk.Frame(master)
l1 = tk.Label(f1, text="pass Word")
l1.pack(side=LEFT)
E1=Entry(f1,bd=5)
E1.pack(side=LEFT)
f4=tk.Frame(master)
l = tk.Label(f4, text="User Name")
l.pack(side=LEFT)
a1=Entry(f4,bd=5)
a1.pack(side=RIGHT)
f3=tk.Frame(master)
B1 = tk.Button(f3, text="New User",bg="blue", command=register_page)
b2=tk.Button(f3,text="Login Now",bg="blue")
b2.pack(side=LEFT)
B1.pack()

f3.pack(side=BOTTOM)
f4.pack(side=TOP)
# second frame - without f2.pack()
f2 = tk.Frame(master)
l8=tk.Label(f2,text="User Name")
l8.pack(side=TOP)
b8=tk.Entry(f2,bd=5)
b8.pack(side=TOP)
l2 = tk.Label(f2, text="Reg.No.")
l3=tk.Entry(f2,bd=5)
l2.pack(side=LEFT)
l3.pack(side=LEFT)
b3=tk.Label(f2,text="Hostel/Block")
b3.pack(side=LEFT)
l4=tk.Entry(f2,bd=5)
l4.pack(side=LEFT)
var = IntVar()
f5=tk.Frame(master)
b4=tk.Label(f5,text="Gender")
b4.pack(side=LEFT)
R1 = Radiobutton(f5, text="Male", variable=var, value=1)
R1.pack( anchor = W ,side=LEFT)
R2 = Radiobutton(f5, text="Female", variable=var, value=2)
R2.pack( anchor = W,side=LEFT )
b5=tk.Label(f5,text="Mobile no")
b5.pack(side=LEFT)
l5=Entry(f5,bd=5)
l5.pack(side=LEFT)
b6=tk.Label(f5,text="Email Id")
b6.pack(side=LEFT)
l6=tk.Entry(f5,bd=5)
l6.pack()
b2 = tk.Button(f2, text="Return Login Page", command=login_page)
b2.pack(anchor= S)
f5.pack(side=BOTTOM)
B2=tk.Button(f5,text="Submit",bg="blue")
B2.pack(side=RIGHT)
# show first frame
f1.pack()
#f2.pack()
master.mainloop()
